
```{r}
library(tidyverse)
```

```{r}
data <- read.csv("absenteeismData.csv") %>% 
  filter(Grade == "All Grades" & Year =='2020-21')
```

```{r}
data2 <- read.csv("demographicData.csv") %>% 
  filter(Year =='2020-21')
```

```{r}
joined_data <- data %>%
  full_join(data2, by="DBN", suffix=c("",".y")) %>%
  select(-ends_with(".y"))
```

```{r}
joined_data <- na.omit(joined_data)
```

```{r}
joined_data$X..Poverty.1[joined_data$X..Poverty.1 == 'Above 95%'] <- '95'
```

```{r}
joined_data$X..Poverty.1 <- gsub("%", "", joined_data$X..Poverty.1)
```

```{r}
joined_data$X..Poverty.1 = as.numeric(as.character(joined_data$X..Poverty.1))
joined_data$X..Chronically.Absent.1 = as.numeric(as.character(joined_data$X..Chronically.Absent.1))
```


````{r}
ggplot(data = joined_data, mapping = aes(x = X..Poverty.1, y = X..Chronically.Absent.1)) +
  geom_point() +
  labs(title = "Students Living in Poverty vs Students Chronically Absent", subtitle = "In NYC schools", x ="Poverty (%)", y ="Chronically Absent (%)")
```



